### PR TITLE
store reconnect URL and reconnect when migration occurs. closes #17

### LINKED ISSUE #17: bot dies when a team migration occurs

### PR DESCRIPTION
**Pull request by ajm188**
@matthewbentley does this seem reasonable?

### CODE REVIEW

**Comment by mtbentley** [comment]
Looks reasonable.  I'll test it before I +1

**Comment by mtbentley** [comment]
Well, IDK how to make slacksoc rebuild using this branch

**Comment by ajm188** [comment]
Hmm. We probably have to do this manually. I'm also not opposed to just merging this in and reverting the merge if necessary.

**Comment by ajm188** [comment]
It's also going to be kind of tricky to test. I say, if the bot can start up and not crash, then we leave it alone. If another migration happens and it doesn't work, then I'll look at the logs and reopen the issue.

**Comment by mtbentley** [comment]
Yeah, just merge it and I'll manually rebuild :+1:

**Pull request merged**
